// THIS IS AUTOGENERATED FILE
#include "inc.h"
#include "glui.h"
#include "ui_def.h"
#include "defs.h"
#include "shader.h"
#include "x16g.h"
#include "x16t.h"

glui_text_t ui_edit_mode =
{
	.base.draw = glui_df_text,
	.base.x = 512,
	.base.y = 384,
	.base.width = 192,
	.base.height = 64,
	.base.align = GLUI_ALIGN_CENTER_CENTER,
	.base.disabled = 1,
	.base.color = {4279242768, 4279242768},
	.base.border_size = 2,
	.base.border_color = {4278214911, 4278214911},
	.color = {4294967295, 4294967295},
};

glui_text_t ui_edit_highlight_title =
{
	.base.draw = glui_df_text,
	.base.align = GLUI_ALIGN_CENTER,
	.color = {4294967295, 4294967295},
};

glui_text_t ui_edit_highlight_textA =
{
	.base.draw = glui_df_text,
	.base.y = 16,
	.base.align = GLUI_ALIGN_CENTER,
	.color = {4294967295, 4294967295},
};

glui_text_t ui_edit_highlight_textB =
{
	.base.draw = glui_df_text,
	.base.y = 16,
	.base.align = GLUI_ALIGN_CENTER,
	.color = {4294967295, 4294967295},
};

glui_text_t ui_edit_highlight_textC =
{
	.base.draw = glui_df_text,
	.base.y = 16,
	.base.align = GLUI_ALIGN_CENTER,
	.color = {4294967295, 4294967295},
};

glui_text_t ui_edit_highlight_textD =
{
	.base.draw = glui_df_text,
	.base.y = 16,
	.base.align = GLUI_ALIGN_CENTER,
	.color = {4294967295, 4294967295},
};

glui_image_t ui_edit_highlight_imgA =
{
	.base.draw = glui_df_image,
	.base.y = 65,
	.base.width = 64,
	.base.height = 64,
	.base.align = GLUI_ALIGN_CENTER_CENTER,
	.coord.s[0] = 0,
	.coord.t[0] = 0,
	.coord.s[1] = 1,
	.coord.t[1] = 1,
};

glui_image_t ui_edit_highlight_imgB =
{
	.base.draw = glui_df_image,
	.base.y = 65,
	.base.width = 64,
	.base.height = 64,
	.base.align = GLUI_ALIGN_CENTER_CENTER,
	.coord.s[0] = 0,
	.coord.t[0] = 0,
	.coord.s[1] = 1,
	.coord.t[1] = 1,
};

glui_image_t ui_edit_highlight_imgC =
{
	.base.draw = glui_df_image,
	.base.y = 65,
	.base.width = 64,
	.base.height = 64,
	.base.align = GLUI_ALIGN_CENTER_CENTER,
	.coord.s[0] = 0,
	.coord.t[0] = 0,
	.coord.s[1] = 1,
	.coord.t[1] = 1,
};

glui_image_t ui_edit_highlight_imgD =
{
	.base.draw = glui_df_image,
	.base.y = 65,
	.base.width = 64,
	.base.height = 64,
	.base.align = GLUI_ALIGN_CENTER_CENTER,
	.coord.s[0] = 0,
	.coord.t[0] = 0,
	.coord.s[1] = 1,
	.coord.t[1] = 1,
};

glui_container_t ui_edit_highlight =
{
	.base.draw = glui_df_container,
	.base.x = 1,
	.base.width = 192,
	.base.height = 152,
	.base.align = GLUI_ALIGN_LEFT_BOT,
	.base.disabled = 1,
	.base.color = {4279242768, 4279242768},
	.base.border_size = 2,
	.base.border_color = {4286611584, 4286611584},
	.count = 9,
	.elements =
	{
		(void*)&ui_edit_highlight_title,
		(void*)&ui_edit_highlight_textA,
		(void*)&ui_edit_highlight_textB,
		(void*)&ui_edit_highlight_textC,
		(void*)&ui_edit_highlight_textD,
		(void*)&ui_edit_highlight_imgA,
		(void*)&ui_edit_highlight_imgB,
		(void*)&ui_edit_highlight_imgC,
		(void*)&ui_edit_highlight_imgD,
	},
};

glui_image_t ui_editor_002_000_000 =
{
	.base.draw = glui_df_image,
	.base.x = 512,
	.base.y = 96,
	.base.width = 512,
	.base.height = 512,
	.base.align = GLUI_ALIGN_CENTER,
	.base.click = uin_gfx_palette_bright,
	.gltex = &x16_gl_tex[X16G_GLTEX_BRIGHT_COLORS],
	.shader = SHADER_FRAGMENT_PALETTE,
	.coord.s[0] = 0,
	.coord.t[0] = 0,
	.coord.s[1] = 1,
	.coord.t[1] = 1,
};

glui_text_t ui_editor_002_000_001 =
{
	.base.draw = glui_df_text,
	.base.x = 512,
	.base.y = 640,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_palette_import,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_000_002 =
{
	.base.draw = glui_df_text,
	.base.x = 128,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.color = {4290822336, 4290822336},
};

glui_text_t ui_gfx_palette_tint_des =
{
	.base.draw = glui_df_text,
	.base.x = 128,
	.base.y = 136,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_palette_tint_des,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_000_004 =
{
	.base.draw = glui_df_text,
	.base.x = 128,
	.base.y = 176,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.color = {4290822336, 4290822336},
};

glui_text_t ui_gfx_palette_tint_mr =
{
	.base.draw = glui_df_text,
	.base.x = 128,
	.base.y = 216,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_palette_tint_mr,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_palette_tint_mg =
{
	.base.draw = glui_df_text,
	.base.x = 128,
	.base.y = 256,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_palette_tint_mg,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_palette_tint_mb =
{
	.base.draw = glui_df_text,
	.base.x = 128,
	.base.y = 296,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_palette_tint_mb,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_000_008 =
{
	.base.draw = glui_df_text,
	.base.x = 128,
	.base.y = 336,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.color = {4290822336, 4290822336},
};

glui_text_t ui_gfx_palette_tint_ar =
{
	.base.draw = glui_df_text,
	.base.x = 128,
	.base.y = 376,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_palette_tint_ar,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_palette_tint_ag =
{
	.base.draw = glui_df_text,
	.base.x = 128,
	.base.y = 416,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_palette_tint_ag,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_palette_tint_ab =
{
	.base.draw = glui_df_text,
	.base.x = 128,
	.base.y = 456,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_palette_tint_ab,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_000_00C =
{
	.base.draw = glui_df_text,
	.base.x = 128,
	.base.y = 536,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_palette_tint,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_000_00D =
{
	.base.draw = glui_df_text,
	.base.x = 896,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.color = {4290822336, 4290822336},
};

glui_text_t ui_gfx_palette_dmg_des =
{
	.base.draw = glui_df_text,
	.base.x = 896,
	.base.y = 136,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_palette_dmg_des,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_000_00F =
{
	.base.draw = glui_df_text,
	.base.x = 896,
	.base.y = 176,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.color = {4290822336, 4290822336},
};

glui_text_t ui_gfx_palette_dmg_add =
{
	.base.draw = glui_df_text,
	.base.x = 896,
	.base.y = 216,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_palette_dmg_add,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_000_011 =
{
	.base.draw = glui_df_text,
	.base.x = 896,
	.base.y = 256,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.color = {4290822336, 4290822336},
};

glui_text_t ui_gfx_palette_dmg_r =
{
	.base.draw = glui_df_text,
	.base.x = 896,
	.base.y = 296,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_palette_dmg_r,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_palette_dmg_g =
{
	.base.draw = glui_df_text,
	.base.x = 896,
	.base.y = 336,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_palette_dmg_g,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_palette_dmg_b =
{
	.base.draw = glui_df_text,
	.base.x = 896,
	.base.y = 376,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_palette_dmg_b,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_000_015 =
{
	.base.draw = glui_df_text,
	.base.x = 896,
	.base.y = 496,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_palette_dmg_single,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_000_016 =
{
	.base.draw = glui_df_text,
	.base.x = 896,
	.base.y = 536,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_palette_dmg_all,
	.color = {4290822336, 4294967295},
};

glui_container_t ui_gfx_palette =
{
	.base.draw = glui_df_container,
	.count = 23,
	.elements =
	{
		(void*)&ui_editor_002_000_000,
		(void*)&ui_editor_002_000_001,
		(void*)&ui_editor_002_000_002,
		(void*)&ui_gfx_palette_tint_des,
		(void*)&ui_editor_002_000_004,
		(void*)&ui_gfx_palette_tint_mr,
		(void*)&ui_gfx_palette_tint_mg,
		(void*)&ui_gfx_palette_tint_mb,
		(void*)&ui_editor_002_000_008,
		(void*)&ui_gfx_palette_tint_ar,
		(void*)&ui_gfx_palette_tint_ag,
		(void*)&ui_gfx_palette_tint_ab,
		(void*)&ui_editor_002_000_00C,
		(void*)&ui_editor_002_000_00D,
		(void*)&ui_gfx_palette_dmg_des,
		(void*)&ui_editor_002_000_00F,
		(void*)&ui_gfx_palette_dmg_add,
		(void*)&ui_editor_002_000_011,
		(void*)&ui_gfx_palette_dmg_r,
		(void*)&ui_gfx_palette_dmg_g,
		(void*)&ui_gfx_palette_dmg_b,
		(void*)&ui_editor_002_000_015,
		(void*)&ui_editor_002_000_016,
	},
};

glui_text_t ui_editor_002_001_000 =
{
	.base.draw = glui_df_text,
	.base.x = 256,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_light_new,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_001_001 =
{
	.base.draw = glui_df_text,
	.base.x = 512,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_light_rename,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_001_002 =
{
	.base.draw = glui_df_text,
	.base.x = 768,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_light_delete,
	.color = {4290822336, 4294967295},
};

glui_image_t ui_editor_002_001_003 =
{
	.base.draw = glui_df_image,
	.base.x = 256,
	.base.y = 160,
	.base.width = 384,
	.base.height = 384,
	.base.align = GLUI_ALIGN_CENTER,
	.gltex = &x16_gl_tex[X16G_GLTEX_PALETTE],
	.coord.s[0] = 0,
	.coord.t[0] = 0,
	.coord.s[1] = 1,
	.coord.t[1] = 0.0625,
};

glui_image_t ui_editor_002_001_004 =
{
	.base.draw = glui_df_image,
	.base.x = 768,
	.base.y = 160,
	.base.width = 384,
	.base.height = 384,
	.base.align = GLUI_ALIGN_CENTER,
	.gltex = &x16_gl_tex[X16G_GLTEX_SHOW_LIGHT],
	.shader = SHADER_FRAGMENT_PALETTE,
	.coord.s[0] = 0,
	.coord.t[0] = 0,
	.coord.s[1] = 1,
	.coord.t[1] = 1,
};

glui_text_t ui_gfx_light_des =
{
	.base.draw = glui_df_text,
	.base.x = 512,
	.base.y = 576,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_light_des,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_light_r =
{
	.base.draw = glui_df_text,
	.base.x = 312,
	.base.y = 616,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_light_r,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_light_g =
{
	.base.draw = glui_df_text,
	.base.x = 512,
	.base.y = 616,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_light_g,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_light_b =
{
	.base.draw = glui_df_text,
	.base.x = 712,
	.base.y = 616,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_light_b,
	.color = {4290822336, 4294967295},
};

glui_container_t ui_gfx_lights =
{
	.base.draw = glui_df_container,
	.count = 9,
	.elements =
	{
		(void*)&ui_editor_002_001_000,
		(void*)&ui_editor_002_001_001,
		(void*)&ui_editor_002_001_002,
		(void*)&ui_editor_002_001_003,
		(void*)&ui_editor_002_001_004,
		(void*)&ui_gfx_light_des,
		(void*)&ui_gfx_light_r,
		(void*)&ui_gfx_light_g,
		(void*)&ui_gfx_light_b,
	},
};

glui_text_t ui_editor_002_002_000_000_000 =
{
	.base.draw = glui_df_text,
	.base.x = 0,
	.base.width = 60,
	.base.height = 162,
	.color = {4278190080, 4278190080},
};

glui_text_t ui_editor_002_002_000_000_001 =
{
	.base.draw = glui_df_text,
	.base.x = 60,
	.base.width = 60,
	.base.height = 162,
	.base.color = {4294506744, 4294506744},
	.color = {4278190080, 4278190080},
};

glui_text_t ui_editor_002_002_000_000_002 =
{
	.base.draw = glui_df_text,
	.base.x = 120,
	.base.width = 136,
	.base.height = 162,
	.color = {4278190080, 4278190080},
};

glui_text_t ui_editor_002_002_000_000_003 =
{
	.base.draw = glui_df_text,
	.base.x = 256,
	.base.width = 136,
	.base.height = 162,
	.base.color = {4294506744, 4294506744},
	.color = {4278190080, 4278190080},
};

glui_dummy_t ui_editor_002_002_000_000_004 =
{
	.base.draw = glui_df_dummy,
	.base.x = 0,
	.base.y = 19,
	.base.width = 392,
	.base.height = 1,
	.base.color = {4279242768, 4279242768},
};

glui_dummy_t ui_editor_002_002_000_000_005 =
{
	.base.draw = glui_df_dummy,
	.base.x = 0,
	.base.y = 20,
	.base.width = 392,
	.base.height = 18,
	.base.color = {134217728, 134217728},
};

glui_dummy_t ui_editor_002_002_000_000_006 =
{
	.base.draw = glui_df_dummy,
	.base.x = 0,
	.base.y = 56,
	.base.width = 392,
	.base.height = 18,
	.base.color = {134217728, 134217728},
};

glui_dummy_t ui_editor_002_002_000_000_007 =
{
	.base.draw = glui_df_dummy,
	.base.x = 0,
	.base.y = 92,
	.base.width = 392,
	.base.height = 18,
	.base.color = {134217728, 134217728},
};

glui_dummy_t ui_editor_002_002_000_000_008 =
{
	.base.draw = glui_df_dummy,
	.base.x = 0,
	.base.y = 128,
	.base.width = 392,
	.base.height = 18,
	.base.color = {134217728, 134217728},
};

glui_text_t ui_editor_002_002_000_000_009 =
{
	.base.draw = glui_df_text,
	.base.x = 100,
	.base.y = 172,
	.base.width = 128,
	.base.height = 24,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_remaps_new,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_002_000_000_00A =
{
	.base.draw = glui_df_text,
	.base.x = 292,
	.base.y = 172,
	.base.width = 128,
	.base.height = 24,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_remaps_del,
	.color = {4290822336, 4294967295},
};

glui_container_t ui_gfx_remaps_ranges =
{
	.base.draw = glui_df_container,
	.base.y = 20,
	.count = 1,
	.elements =
	{
		NULL,
	},
};

glui_container_t ui_gfx_remap_table =
{
	.base.draw = glui_df_container,
	.base.x = 8,
	.base.y = 8,
	.base.width = 392,
	.base.height = 164,
	.base.color = {4294967295, 4294967295},
	.count = 12,
	.elements =
	{
		(void*)&ui_editor_002_002_000_000_000,
		(void*)&ui_editor_002_002_000_000_001,
		(void*)&ui_editor_002_002_000_000_002,
		(void*)&ui_editor_002_002_000_000_003,
		(void*)&ui_editor_002_002_000_000_004,
		(void*)&ui_editor_002_002_000_000_005,
		(void*)&ui_editor_002_002_000_000_006,
		(void*)&ui_editor_002_002_000_000_007,
		(void*)&ui_editor_002_002_000_000_008,
		(void*)&ui_editor_002_002_000_000_009,
		(void*)&ui_editor_002_002_000_000_00A,
		(void*)&ui_gfx_remaps_ranges,
	},
};

glui_container_t ui_editor_002_002_000 =
{
	.base.draw = glui_df_container,
	.base.x = 512,
	.base.y = 496,
	.base.width = 408,
	.base.height = 210,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4279242768, 4279242768},
	.count = 1,
	.elements =
	{
		(void*)&ui_gfx_remap_table,
	},
};

glui_image_t ui_editor_002_002_001 =
{
	.base.draw = glui_df_image,
	.base.x = 256,
	.base.y = 96,
	.base.width = 384,
	.base.height = 384,
	.base.align = GLUI_ALIGN_CENTER,
	.base.click = uin_gfx_remap_color,
	.gltex = &x16_gl_tex[X16G_GLTEX_PALETTE],
	.coord.s[0] = 0,
	.coord.t[0] = 0,
	.coord.s[1] = 1,
	.coord.t[1] = 0.0625,
};

glui_image_t ui_editor_002_002_002 =
{
	.base.draw = glui_df_image,
	.base.x = 768,
	.base.y = 96,
	.base.width = 384,
	.base.height = 384,
	.base.align = GLUI_ALIGN_CENTER,
	.gltex = &x16_gl_tex[X16G_GLTEX_SHOW_TEXTURE],
	.shader = SHADER_FRAGMENT_PALETTE,
	.coord.s[0] = 0,
	.coord.t[0] = 0,
	.coord.s[1] = 1,
	.coord.t[1] = 1,
};

glui_text_t ui_gfx_remap_color =
{
	.base.draw = glui_df_text,
	.base.x = 256,
	.base.y = 80,
	.color = {4286611584, 4286611584},
};

glui_container_t ui_gfx_remaps =
{
	.base.draw = glui_df_container,
	.count = 4,
	.elements =
	{
		(void*)&ui_editor_002_002_000,
		(void*)&ui_editor_002_002_001,
		(void*)&ui_editor_002_002_002,
		(void*)&ui_gfx_remap_color,
	},
};

glui_text_t ui_gfx_plane_variant_name =
{
	.base.draw = glui_df_text,
	.base.x = 512,
	.base.y = 68,
	.color = {4290822336, 4290822336},
};

glui_text_t ui_editor_002_003_001 =
{
	.base.draw = glui_df_text,
	.base.x = 200,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_plane_new4,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_003_002 =
{
	.base.draw = glui_df_text,
	.base.x = 408,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_plane_new8,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_003_003 =
{
	.base.draw = glui_df_text,
	.base.x = 616,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_plane_rename,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_003_004 =
{
	.base.draw = glui_df_text,
	.base.x = 824,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_plane_delete,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_003_005 =
{
	.base.draw = glui_df_text,
	.base.x = 200,
	.base.y = 144,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_plane_import,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_plane_import_raw =
{
	.base.draw = glui_df_text,
	.base.x = 408,
	.base.y = 144,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_plane_import_raw,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_plane_variant =
{
	.base.draw = glui_df_text,
	.base.x = 408,
	.base.y = 144,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_plane_variant,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_plane_renvar =
{
	.base.draw = glui_df_text,
	.base.x = 616,
	.base.y = 144,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_plane_renvar,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_plane_delvar =
{
	.base.draw = glui_df_text,
	.base.x = 824,
	.base.y = 144,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_plane_delvar,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_plane_display =
{
	.base.draw = glui_df_text,
	.base.x = 304,
	.base.y = 192,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_plane_display,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_003_00B_000 =
{
	.base.draw = glui_df_text,
	.base.x = 24,
	.base.y = 256,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_LEFT,
	.base.custom = 0,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_plane_effect_btn,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_003_00B_001 =
{
	.base.draw = glui_df_text,
	.base.x = 24,
	.base.y = 304,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_LEFT,
	.base.custom = 1,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_plane_effect_btn,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_003_00B_002 =
{
	.base.draw = glui_df_text,
	.base.x = 24,
	.base.y = 352,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_LEFT,
	.base.custom = 2,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_plane_effect_btn,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_003_00B_003 =
{
	.base.draw = glui_df_text,
	.base.x = 24,
	.base.y = 400,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_LEFT,
	.base.custom = 3,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_plane_effect_btn,
	.color = {4290822336, 4294967295},
};

glui_container_t ui_gfx_plane_effect =
{
	.base.draw = glui_df_container,
	.count = 4,
	.elements =
	{
		(void*)&ui_editor_002_003_00B_000,
		(void*)&ui_editor_002_003_00B_001,
		(void*)&ui_editor_002_003_00B_002,
		(void*)&ui_editor_002_003_00B_003,
	},
};

glui_text_t ui_gfx_plane_variant_pl =
{
	.base.draw = glui_df_text,
	.base.x = 0,
	.base.disabled = 1,
	.color = {4290822336, 4290822336},
};

glui_text_t ui_gfx_plane_variant_pr =
{
	.base.draw = glui_df_text,
	.base.x = 296,
	.base.disabled = 1,
	.color = {4290822336, 4290822336},
};

glui_container_t ui_gfx_plane_variant_box =
{
	.base.draw = glui_df_container,
	.base.x = 848,
	.base.y = 252,
	.base.width = 296,
	.base.height = 296,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4279242768, 4279242768},
	.count = 2,
	.elements =
	{
		(void*)&ui_gfx_plane_variant_pl,
		(void*)&ui_gfx_plane_variant_pr,
	},
};

glui_image_t ui_gfx_plane_texture =
{
	.base.draw = glui_df_image,
	.base.x = 512,
	.base.y = 448,
	.base.width = 384,
	.base.height = 384,
	.base.align = GLUI_ALIGN_CENTER_CENTER,
	.gltex = &x16_gl_tex[X16G_GLTEX_SHOW_TEXTURE],
	.shader = SHADER_FRAGMENT_PALETTE,
	.coord.s[0] = 0,
	.coord.t[0] = 0,
	.coord.s[1] = 1,
	.coord.t[1] = 1,
};

glui_image_t ui_gfx_plane_cmaps =
{
	.base.draw = glui_df_image,
	.base.x = 848,
	.base.y = 256,
	.base.width = 288,
	.base.height = 288,
	.base.align = GLUI_ALIGN_CENTER,
	.base.click = uin_gfx_plane_colormap,
	.gltex = &x16_gl_tex[X16G_GLTEX_BRIGHT_COLORS],
	.shader = SHADER_FRAGMENT_PALETTE,
	.coord.s[0] = 0,
	.coord.t[0] = 0,
	.coord.s[1] = 1,
	.coord.t[1] = 1,
};

glui_container_t ui_gfx_planes =
{
	.base.draw = glui_df_container,
	.count = 15,
	.elements =
	{
		(void*)&ui_gfx_plane_variant_name,
		(void*)&ui_editor_002_003_001,
		(void*)&ui_editor_002_003_002,
		(void*)&ui_editor_002_003_003,
		(void*)&ui_editor_002_003_004,
		(void*)&ui_editor_002_003_005,
		(void*)&ui_gfx_plane_import_raw,
		(void*)&ui_gfx_plane_variant,
		(void*)&ui_gfx_plane_renvar,
		(void*)&ui_gfx_plane_delvar,
		(void*)&ui_gfx_plane_display,
		(void*)&ui_gfx_plane_effect,
		(void*)&ui_gfx_plane_variant_box,
		(void*)&ui_gfx_plane_texture,
		(void*)&ui_gfx_plane_cmaps,
	},
};

glui_text_t ui_gfx_wall_variant_name =
{
	.base.draw = glui_df_text,
	.base.x = 512,
	.base.y = 68,
	.color = {4290822336, 4290822336},
};

glui_text_t ui_gfx_wall_variant_info =
{
	.base.draw = glui_df_text,
	.base.x = 512,
	.base.y = 644,
	.color = {4290822336, 4290822336},
};

glui_text_t ui_gfx_wall_resolution =
{
	.base.draw = glui_df_text,
	.base.x = 200,
	.base.y = 48,
	.color = {4290822336, 4290822336},
};

glui_text_t ui_gfx_wall_info =
{
	.base.draw = glui_df_text,
	.base.x = 512,
	.base.y = 208,
};

glui_text_t ui_editor_002_004_004 =
{
	.base.draw = glui_df_text,
	.base.x = 624,
	.base.y = 52,
	.base.width = 32,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4279242768, 4286611584},
	.base.click = uin_gfx_wall_right,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_004_005 =
{
	.base.draw = glui_df_text,
	.base.x = 400,
	.base.y = 52,
	.base.width = 32,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4279242768, 4286611584},
	.base.click = uin_gfx_wall_left,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_wall_import_raw =
{
	.base.draw = glui_df_text,
	.base.x = 200,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_wall_import,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_004_007 =
{
	.base.draw = glui_df_text,
	.base.x = 408,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_wall_new,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_004_008 =
{
	.base.draw = glui_df_text,
	.base.x = 616,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_wall_rename,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_004_009 =
{
	.base.draw = glui_df_text,
	.base.x = 824,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_wall_delete,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_004_00A =
{
	.base.draw = glui_df_text,
	.base.x = 200,
	.base.y = 144,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_wall_import,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_004_00B =
{
	.base.draw = glui_df_text,
	.base.x = 408,
	.base.y = 144,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_wall_variant,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_004_00C =
{
	.base.draw = glui_df_text,
	.base.x = 616,
	.base.y = 144,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_wall_renvar,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_004_00D =
{
	.base.draw = glui_df_text,
	.base.x = 824,
	.base.y = 144,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_wall_delvar,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_004_00E =
{
	.base.draw = glui_df_text,
	.base.x = 824,
	.base.y = 192,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_wall_fullbright_all,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_wall_display =
{
	.base.draw = glui_df_text,
	.base.x = 512,
	.base.y = 192,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_wall_display,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_004_010_000 =
{
	.base.draw = glui_df_text,
	.base.x = 24,
	.base.y = 256,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_LEFT,
	.base.custom = 0,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_wall_animation_btn,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_004_010_001 =
{
	.base.draw = glui_df_text,
	.base.x = 24,
	.base.y = 304,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_LEFT,
	.base.custom = 1,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_wall_animation_btn,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_004_010_002 =
{
	.base.draw = glui_df_text,
	.base.x = 24,
	.base.y = 352,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_LEFT,
	.base.custom = 2,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_wall_animation_btn,
	.color = {4290822336, 4294967295},
};

glui_container_t ui_gfx_wall_animation =
{
	.base.draw = glui_df_container,
	.count = 3,
	.elements =
	{
		(void*)&ui_editor_002_004_010_000,
		(void*)&ui_editor_002_004_010_001,
		(void*)&ui_editor_002_004_010_002,
	},
};

glui_image_t ui_gfx_wall_texture =
{
	.base.draw = glui_df_image,
	.base.x = 512,
	.base.y = 448,
	.base.width = 384,
	.base.height = 384,
	.base.align = GLUI_ALIGN_CENTER_CENTER,
	.gltex = &x16_gl_tex[X16G_GLTEX_SHOW_TEXTURE],
	.shader = SHADER_FRAGMENT_PALETTE_LIGHT,
	.coord.s[0] = 0,
	.coord.t[0] = 0,
	.coord.s[1] = 1,
	.coord.t[1] = 1,
};

glui_container_t ui_gfx_walls =
{
	.base.draw = glui_df_container,
	.count = 18,
	.elements =
	{
		(void*)&ui_gfx_wall_variant_name,
		(void*)&ui_gfx_wall_variant_info,
		(void*)&ui_gfx_wall_resolution,
		(void*)&ui_gfx_wall_info,
		(void*)&ui_editor_002_004_004,
		(void*)&ui_editor_002_004_005,
		(void*)&ui_gfx_wall_import_raw,
		(void*)&ui_editor_002_004_007,
		(void*)&ui_editor_002_004_008,
		(void*)&ui_editor_002_004_009,
		(void*)&ui_editor_002_004_00A,
		(void*)&ui_editor_002_004_00B,
		(void*)&ui_editor_002_004_00C,
		(void*)&ui_editor_002_004_00D,
		(void*)&ui_editor_002_004_00E,
		(void*)&ui_gfx_wall_display,
		(void*)&ui_gfx_wall_animation,
		(void*)&ui_gfx_wall_texture,
	},
};

glui_image_t ui_gfx_sprite_texture =
{
	.base.draw = glui_df_image,
	.base.x = 512,
	.base.y = 448,
	.base.width = 384,
	.base.height = 384,
	.base.align = GLUI_ALIGN_CENTER_CENTER,
	.gltex = &x16_gl_tex[X16G_GLTEX_SHOW_TEXTURE],
	.shader = SHADER_FRAGMENT_PALETTE_LIGHT,
	.coord.s[0] = 0,
	.coord.t[0] = 0,
	.coord.s[1] = 1,
	.coord.t[1] = 1,
};

glui_dummy_t ui_editor_002_005_001_000 =
{
	.base.draw = glui_df_dummy,
	.base.x = -256,
	.base.y = 256,
	.base.width = 512,
	.base.height = 1,
	.base.color = {4294967295, 4294967295},
};

glui_container_t ui_gfx_sprite_origin =
{
	.base.draw = glui_df_container,
	.base.x = 512,
	.base.y = 448,
	.base.width = 1,
	.base.height = 512,
	.base.align = GLUI_ALIGN_CENTER_CENTER,
	.base.disabled = 1,
	.base.color = {4294967295, 4294967295},
	.count = 1,
	.elements =
	{
		(void*)&ui_editor_002_005_001_000,
	},
};

glui_text_t ui_gfx_sprite_variant_name =
{
	.base.draw = glui_df_text,
	.base.x = 512,
	.base.y = 68,
	.color = {4290822336, 4290822336},
};

glui_text_t ui_gfx_sprite_variant_info =
{
	.base.draw = glui_df_text,
	.base.x = 512,
	.base.y = 644,
	.color = {4290822336, 4290822336},
};

glui_text_t ui_gfx_sprite_resolution =
{
	.base.draw = glui_df_text,
	.base.x = 200,
	.base.y = 64,
	.color = {4290822336, 4290822336},
};

glui_text_t ui_gfx_sprite_info =
{
	.base.draw = glui_df_text,
	.base.x = 512,
	.base.y = 208,
};

glui_text_t ui_editor_002_005_006 =
{
	.base.draw = glui_df_text,
	.base.x = 200,
	.base.y = 644,
	.base.align = GLUI_ALIGN_CENTER,
	.color = {4290822336, 4290822336},
};

glui_text_t ui_editor_002_005_007 =
{
	.base.draw = glui_df_text,
	.base.x = 824,
	.base.y = 644,
	.base.align = GLUI_ALIGN_CENTER,
	.color = {4290822336, 4290822336},
};

glui_text_t ui_editor_002_005_008 =
{
	.base.draw = glui_df_text,
	.base.x = 624,
	.base.y = 52,
	.base.width = 32,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4279242768, 4286611584},
	.base.click = uin_gfx_sprite_right,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_005_009 =
{
	.base.draw = glui_df_text,
	.base.x = 400,
	.base.y = 52,
	.base.width = 32,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4279242768, 4286611584},
	.base.click = uin_gfx_sprite_left,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_sprite_import_raw =
{
	.base.draw = glui_df_text,
	.base.x = 200,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_sprite_import,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_005_00B =
{
	.base.draw = glui_df_text,
	.base.x = 408,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_sprite_new,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_005_00C =
{
	.base.draw = glui_df_text,
	.base.x = 616,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_sprite_rename,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_005_00D =
{
	.base.draw = glui_df_text,
	.base.x = 824,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_sprite_delete,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_005_00E =
{
	.base.draw = glui_df_text,
	.base.x = 200,
	.base.y = 144,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_sprite_import,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_005_00F =
{
	.base.draw = glui_df_text,
	.base.x = 408,
	.base.y = 144,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_sprite_variant,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_005_010 =
{
	.base.draw = glui_df_text,
	.base.x = 616,
	.base.y = 144,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_sprite_renvar,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_005_011 =
{
	.base.draw = glui_df_text,
	.base.x = 824,
	.base.y = 144,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_sprite_delvar,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_sprite_show_origin =
{
	.base.draw = glui_df_text,
	.base.x = 200,
	.base.y = 192,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_sprite_show_origin,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_005_013 =
{
	.base.draw = glui_df_text,
	.base.x = 824,
	.base.y = 192,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_sprite_mirror,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_sprite_offs_x =
{
	.base.draw = glui_df_text,
	.base.x = 200,
	.base.y = 660,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_sprite_offs_x,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_sprite_offs_y =
{
	.base.draw = glui_df_text,
	.base.x = 824,
	.base.y = 660,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_sprite_offs_y,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_sprite_display =
{
	.base.draw = glui_df_text,
	.base.x = 512,
	.base.y = 192,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_sprite_display,
	.color = {4290822336, 4294967295},
};

glui_container_t ui_gfx_sprites =
{
	.base.draw = glui_df_container,
	.count = 23,
	.elements =
	{
		(void*)&ui_gfx_sprite_texture,
		(void*)&ui_gfx_sprite_origin,
		(void*)&ui_gfx_sprite_variant_name,
		(void*)&ui_gfx_sprite_variant_info,
		(void*)&ui_gfx_sprite_resolution,
		(void*)&ui_gfx_sprite_info,
		(void*)&ui_editor_002_005_006,
		(void*)&ui_editor_002_005_007,
		(void*)&ui_editor_002_005_008,
		(void*)&ui_editor_002_005_009,
		(void*)&ui_gfx_sprite_import_raw,
		(void*)&ui_editor_002_005_00B,
		(void*)&ui_editor_002_005_00C,
		(void*)&ui_editor_002_005_00D,
		(void*)&ui_editor_002_005_00E,
		(void*)&ui_editor_002_005_00F,
		(void*)&ui_editor_002_005_010,
		(void*)&ui_editor_002_005_011,
		(void*)&ui_gfx_sprite_show_origin,
		(void*)&ui_editor_002_005_013,
		(void*)&ui_gfx_sprite_offs_x,
		(void*)&ui_gfx_sprite_offs_y,
		(void*)&ui_gfx_sprite_display,
	},
};

glui_text_t ui_gfx_wpn_variant_name =
{
	.base.draw = glui_df_text,
	.base.x = 512,
	.base.y = 68,
	.color = {4290822336, 4290822336},
};

glui_text_t ui_editor_002_006_001 =
{
	.base.draw = glui_df_text,
	.base.x = 624,
	.base.y = 52,
	.base.width = 32,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4279242768, 4286611584},
	.base.click = uin_gfx_wpn_right,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_006_002 =
{
	.base.draw = glui_df_text,
	.base.x = 400,
	.base.y = 52,
	.base.width = 32,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4279242768, 4286611584},
	.base.click = uin_gfx_wpn_left,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_006_003 =
{
	.base.draw = glui_df_text,
	.base.x = 408,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_wpn_new,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_006_004 =
{
	.base.draw = glui_df_text,
	.base.x = 616,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_wpn_rename,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_006_005 =
{
	.base.draw = glui_df_text,
	.base.x = 824,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_wpn_delete,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_006_006 =
{
	.base.draw = glui_df_text,
	.base.x = 200,
	.base.y = 144,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_wpn_import,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_006_007 =
{
	.base.draw = glui_df_text,
	.base.x = 408,
	.base.y = 144,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_wpn_variant,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_wpn_info =
{
	.base.draw = glui_df_text,
	.base.x = 200,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
};

glui_text_t ui_editor_002_006_009 =
{
	.base.draw = glui_df_text,
	.base.x = 824,
	.base.y = 144,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_wpn_delvar,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_wpn_part_pl =
{
	.base.draw = glui_df_text,
	.base.x = 0,
	.color = {4290822336, 4290822336},
};

glui_text_t ui_gfx_wpn_part_pr =
{
	.base.draw = glui_df_text,
	.base.x = 192,
	.color = {4290822336, 4290822336},
};

glui_text_t ui_gfx_wpn_part_text_l =
{
	.base.draw = glui_df_text,
	.base.x = 96,
	.base.y = 2,
	.base.width = 96,
	.base.height = 529,
	.base.align = GLUI_ALIGN_RIGHT,
	.base.click = uin_gfx_wpn_part_sel,
	.color = {4290822336, 4290822336},
};

glui_text_t ui_gfx_wpn_part_text_r =
{
	.base.draw = glui_df_text,
	.base.x = 96,
	.base.y = 2,
	.base.width = 96,
	.base.height = 529,
	.base.align = GLUI_ALIGN_LEFT,
	.base.click = uin_gfx_wpn_part_sel,
	.color = {4290822336, 4290822336},
};

glui_container_t ui_gfx_wpn_part_box =
{
	.base.draw = glui_df_container,
	.base.x = 1000,
	.base.y = 192,
	.base.width = 192,
	.base.height = 533,
	.base.align = GLUI_ALIGN_RIGHT,
	.base.color = {4279242768, 4279242768},
	.count = 4,
	.elements =
	{
		(void*)&ui_gfx_wpn_part_pl,
		(void*)&ui_gfx_wpn_part_pr,
		(void*)&ui_gfx_wpn_part_text_l,
		(void*)&ui_gfx_wpn_part_text_r,
	},
};

glui_text_t ui_gfx_wpn_part_apply =
{
	.base.draw = glui_df_text,
	.base.x = 616,
	.base.y = 144,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_wpn_part_apply,
	.color = {4278214911, 4278255615},
};

glui_text_t ui_gfx_wpn_part_btn0 =
{
	.base.draw = glui_df_text,
	.base.x = 200,
	.base.y = 690,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_wpn_part_btn0,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_wpn_part_btn1 =
{
	.base.draw = glui_df_text,
	.base.x = 408,
	.base.y = 690,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_wpn_part_btn1,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_wpn_part_btn2 =
{
	.base.draw = glui_df_text,
	.base.x = 616,
	.base.y = 690,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_wpn_part_btn2,
	.color = {4290822336, 4294967295},
};

glui_image_t ui_gfx_wpn_texture =
{
	.base.draw = glui_df_image,
	.base.click = uin_gfx_wpn_part_pos,
	.gltex = &x16_gl_tex[X16G_GLTEX_SHOW_TEXTURE],
	.shader = SHADER_FRAGMENT_PALETTE_LIGHT,
	.coord.s[0] = 0,
	.coord.t[0] = 0,
	.coord.s[1] = 1,
	.coord.t[1] = 1,
};

glui_container_t ui_gfx_wpn_part_rect_box =
{
	.base.draw = glui_df_container,
	.priority = 1,
	.count = 1,
	.elements =
	{
		NULL,
	},
};

glui_container_t ui_gfx_weapons =
{
	.base.draw = glui_df_container,
	.count = 17,
	.elements =
	{
		(void*)&ui_gfx_wpn_variant_name,
		(void*)&ui_editor_002_006_001,
		(void*)&ui_editor_002_006_002,
		(void*)&ui_editor_002_006_003,
		(void*)&ui_editor_002_006_004,
		(void*)&ui_editor_002_006_005,
		(void*)&ui_editor_002_006_006,
		(void*)&ui_editor_002_006_007,
		(void*)&ui_gfx_wpn_info,
		(void*)&ui_editor_002_006_009,
		(void*)&ui_gfx_wpn_part_box,
		(void*)&ui_gfx_wpn_part_apply,
		(void*)&ui_gfx_wpn_part_btn0,
		(void*)&ui_gfx_wpn_part_btn1,
		(void*)&ui_gfx_wpn_part_btn2,
		(void*)&ui_gfx_wpn_texture,
		(void*)&ui_gfx_wpn_part_rect_box,
	},
};

glui_text_t ui_editor_002_007_000 =
{
	.base.draw = glui_df_text,
	.base.x = 200,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_sky_import,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_007_001 =
{
	.base.draw = glui_df_text,
	.base.x = 408,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_sky_new,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_007_002 =
{
	.base.draw = glui_df_text,
	.base.x = 616,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_sky_rename,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_007_003 =
{
	.base.draw = glui_df_text,
	.base.x = 824,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_sky_delete,
	.color = {4290822336, 4294967295},
};

glui_image_t ui_gfx_sky_texture =
{
	.base.draw = glui_df_image,
	.base.x = 512,
	.base.y = 384,
	.base.width = 1024,
	.base.height = 240,
	.base.align = GLUI_ALIGN_CENTER_CENTER,
	.gltex = &x16_gl_tex[X16G_GLTEX_SHOW_TEXTURE],
	.shader = SHADER_FRAGMENT_PALETTE,
	.coord.s[0] = 0,
	.coord.t[0] = 0,
	.coord.s[1] = 1,
	.coord.t[1] = 1,
};

glui_container_t ui_gfx_skies =
{
	.base.draw = glui_df_container,
	.count = 5,
	.elements =
	{
		(void*)&ui_editor_002_007_000,
		(void*)&ui_editor_002_007_001,
		(void*)&ui_editor_002_007_002,
		(void*)&ui_editor_002_007_003,
		(void*)&ui_gfx_sky_texture,
	},
};

glui_text_t ui_editor_002_008_000 =
{
	.base.draw = glui_df_text,
	.base.x = 408,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_hud_import,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_hud_color =
{
	.base.draw = glui_df_text,
	.base.x = 616,
	.base.y = 96,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_gfx_hud_color,
	.color = {4290822336, 4294967295},
};

glui_image_t ui_gfx_hud_texture =
{
	.base.draw = glui_df_image,
	.base.x = 512,
	.base.y = 384,
	.base.align = GLUI_ALIGN_CENTER_CENTER,
	.gltex = &x16_gl_tex[X16G_GLTEX_SHOW_TEXTURE],
	.shader = SHADER_FRAGMENT_PALETTE,
	.coord.s[0] = 0,
	.coord.t[0] = 0,
	.coord.s[1] = 1,
	.coord.t[1] = 1,
};

glui_container_t ui_gfx_hud =
{
	.base.draw = glui_df_container,
	.base.color = {4290822144, 4290822144},
	.count = 3,
	.elements =
	{
		(void*)&ui_editor_002_008_000,
		(void*)&ui_gfx_hud_color,
		(void*)&ui_gfx_hud_texture,
	},
};

glui_text_t ui_gfx_idx =
{
	.base.draw = glui_df_text,
	.base.x = 512,
	.base.y = 8,
	.color = {4290822336, 4290822336},
};

glui_text_t ui_gfx_title =
{
	.base.draw = glui_df_text,
	.base.x = 512,
	.base.y = 48,
	.color = {4290822336, 4290822336},
};

glui_text_t ui_editor_002_00B =
{
	.base.draw = glui_df_text,
	.base.x = 624,
	.base.y = 12,
	.base.width = 32,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4279242768, 4286611584},
	.base.click = uin_gfx_right,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_002_00C =
{
	.base.draw = glui_df_text,
	.base.x = 400,
	.base.y = 12,
	.base.width = 32,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4279242768, 4286611584},
	.base.click = uin_gfx_left,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_gfx_palette_txt =
{
	.base.draw = glui_df_text,
	.base.x = 48,
	.base.y = 1,
	.base.width = 96,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {0, 4278196288},
	.base.click = uin_gfx_mode_click,
	.color = {4290822336, 4278255615},
};

glui_text_t ui_gfx_lights_txt =
{
	.base.draw = glui_df_text,
	.base.x = 144,
	.base.y = 1,
	.base.width = 96,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {0, 4278196288},
	.base.click = uin_gfx_mode_click,
	.color = {4290822336, 4278255615},
};

glui_text_t ui_gfx_remaps_txt =
{
	.base.draw = glui_df_text,
	.base.x = 240,
	.base.y = 1,
	.base.width = 96,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {0, 4278196288},
	.base.click = uin_gfx_mode_click,
	.color = {4290822336, 4278255615},
};

glui_text_t ui_gfx_planes_txt =
{
	.base.draw = glui_df_text,
	.base.x = 336,
	.base.y = 1,
	.base.width = 96,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {0, 4278196288},
	.base.click = uin_gfx_mode_click,
	.color = {4290822336, 4278255615},
};

glui_text_t ui_gfx_walls_txt =
{
	.base.draw = glui_df_text,
	.base.x = 432,
	.base.y = 1,
	.base.width = 96,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {0, 4278196288},
	.base.click = uin_gfx_mode_click,
	.color = {4290822336, 4278255615},
};

glui_text_t ui_gfx_sprites_txt =
{
	.base.draw = glui_df_text,
	.base.x = 528,
	.base.y = 1,
	.base.width = 96,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {0, 4278196288},
	.base.click = uin_gfx_mode_click,
	.color = {4290822336, 4278255615},
};

glui_text_t ui_gfx_weapons_txt =
{
	.base.draw = glui_df_text,
	.base.x = 624,
	.base.y = 1,
	.base.width = 96,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {0, 4278196288},
	.base.click = uin_gfx_mode_click,
	.color = {4290822336, 4278255615},
};

glui_text_t ui_gfx_skies_txt =
{
	.base.draw = glui_df_text,
	.base.x = 720,
	.base.y = 1,
	.base.width = 96,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {0, 4278196288},
	.base.click = uin_gfx_mode_click,
	.color = {4290822336, 4278255615},
};

glui_text_t ui_gfx_hud_txt =
{
	.base.draw = glui_df_text,
	.base.x = 818,
	.base.y = 1,
	.base.width = 96,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {0, 4278196288},
	.base.click = uin_gfx_mode_click,
	.color = {4290822336, 4278255615},
};

glui_container_t ui_editor_002_00D =
{
	.base.draw = glui_df_container,
	.base.x = 512,
	.base.y = 735,
	.base.width = 867,
	.base.height = 48,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4279242768, 4279242768},
	.base.border_size = 2,
	.base.border_color = {4278239424, 4278239424},
	.count = 9,
	.elements =
	{
		(void*)&ui_gfx_palette_txt,
		(void*)&ui_gfx_lights_txt,
		(void*)&ui_gfx_remaps_txt,
		(void*)&ui_gfx_planes_txt,
		(void*)&ui_gfx_walls_txt,
		(void*)&ui_gfx_sprites_txt,
		(void*)&ui_gfx_weapons_txt,
		(void*)&ui_gfx_skies_txt,
		(void*)&ui_gfx_hud_txt,
	},
};

glui_container_t ui_edit_gfx =
{
	.base.draw = glui_df_container,
	.base.disabled = 1,
	.input = uin_gfx_input,
	.priority = 100,
	.count = 14,
	.elements =
	{
		(void*)&ui_gfx_palette,
		(void*)&ui_gfx_lights,
		(void*)&ui_gfx_remaps,
		(void*)&ui_gfx_planes,
		(void*)&ui_gfx_walls,
		(void*)&ui_gfx_sprites,
		(void*)&ui_gfx_weapons,
		(void*)&ui_gfx_skies,
		(void*)&ui_gfx_hud,
		(void*)&ui_gfx_idx,
		(void*)&ui_gfx_title,
		(void*)&ui_editor_002_00B,
		(void*)&ui_editor_002_00C,
		(void*)&ui_editor_002_00D,
	},
};

glui_image_t ui_thing_state_preview =
{
	.base.draw = glui_df_image,
	.base.align = GLUI_ALIGN_BOT_CENTER,
	.base.click = uin_thing_state_origin,
	.gltex = &x16_thing_texture[0],
	.shader = SHADER_FRAGMENT_PALETTE,
	.coord.s[0] = 0,
	.coord.t[0] = 0,
	.coord.s[1] = 1,
	.coord.t[1] = 1,
};

glui_dummy_t ui_editor_003_000_001_000 =
{
	.base.draw = glui_df_dummy,
	.base.x = -128,
	.base.y = 128,
	.base.width = 256,
	.base.height = 1,
	.base.color = {4294967295, 4294967295},
};

glui_container_t ui_thing_state_origin =
{
	.base.draw = glui_df_container,
	.base.x = 400,
	.base.y = 460,
	.base.width = 1,
	.base.height = 256,
	.base.align = GLUI_ALIGN_CENTER_CENTER,
	.base.color = {4294967295, 4294967295},
	.priority = 1,
	.count = 1,
	.elements =
	{
		(void*)&ui_editor_003_000_001_000,
	},
};

glui_text_t ui_thing_idx =
{
	.base.draw = glui_df_text,
	.base.x = 512,
	.base.y = 10,
	.base.width = 160,
	.base.height = 40,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {0, 4279242768},
	.base.click = uin_thing_select,
	.color = {4290822336, 4290822336},
};

glui_text_t ui_thing_title =
{
	.base.draw = glui_df_text,
	.base.x = 512,
	.base.y = 50,
	.base.width = 192,
	.base.height = 28,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4279242768, 4280295456},
	.base.click = uin_thing_rename,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_003_000_004 =
{
	.base.draw = glui_df_text,
	.base.x = 624,
	.base.y = 12,
	.base.width = 32,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4279242768, 4286611584},
	.base.click = uin_thing_right,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_003_000_005 =
{
	.base.draw = glui_df_text,
	.base.x = 400,
	.base.y = 12,
	.base.width = 32,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4279242768, 4286611584},
	.base.click = uin_thing_left,
	.color = {4290822336, 4294967295},
};

glui_container_t ui_thing_attrs =
{
	.base.draw = glui_df_container,
	.base.x = 1008,
	.base.y = 16,
	.base.width = 208,
	.base.align = GLUI_ALIGN_RIGHT,
	.base.color = {4279242768, 4279242768},
	.count = 1,
	.elements =
	{
		NULL,
	},
};

glui_container_t ui_thing_flags =
{
	.base.draw = glui_df_container,
	.base.x = 1008,
	.base.width = 208,
	.base.align = GLUI_ALIGN_RIGHT,
	.base.color = {4279242768, 4279242768},
	.count = 1,
	.elements =
	{
		NULL,
	},
};

glui_container_t ui_thing_anims =
{
	.base.draw = glui_df_container,
	.base.x = 1008,
	.base.width = 208,
	.base.align = GLUI_ALIGN_RIGHT,
	.base.color = {4279242768, 4279242768},
	.count = 1,
	.elements =
	{
		NULL,
	},
};

glui_text_t ui_thing_state_anim =
{
	.base.draw = glui_df_text,
	.base.x = 384,
	.color = {4294967295, 4294967295},
};

glui_text_t ui_editor_003_000_009_001_000 =
{
	.base.draw = glui_df_text,
	.base.x = 0,
	.base.width = 40,
	.base.height = 180,
	.color = {4278190080, 4278190080},
};

glui_text_t ui_editor_003_000_009_001_001 =
{
	.base.draw = glui_df_text,
	.base.x = 40,
	.base.width = 116,
	.base.height = 180,
	.base.color = {4294506744, 4294506744},
	.color = {4278190080, 4278190080},
};

glui_text_t ui_editor_003_000_009_001_002 =
{
	.base.draw = glui_df_text,
	.base.x = 156,
	.base.width = 44,
	.base.height = 180,
	.color = {4278190080, 4278190080},
};

glui_text_t ui_editor_003_000_009_001_003 =
{
	.base.draw = glui_df_text,
	.base.x = 200,
	.base.width = 44,
	.base.height = 180,
	.base.color = {4294506744, 4294506744},
	.color = {4278190080, 4278190080},
};

glui_text_t ui_editor_003_000_009_001_004 =
{
	.base.draw = glui_df_text,
	.base.x = 244,
	.base.width = 44,
	.base.height = 180,
	.color = {4278190080, 4278190080},
};

glui_text_t ui_editor_003_000_009_001_005 =
{
	.base.draw = glui_df_text,
	.base.x = 288,
	.base.width = 116,
	.base.height = 180,
	.base.color = {4294506744, 4294506744},
	.color = {4278190080, 4278190080},
};

glui_text_t ui_editor_003_000_009_001_006 =
{
	.base.draw = glui_df_text,
	.base.x = 404,
	.base.width = 116,
	.base.height = 180,
	.color = {4278190080, 4278190080},
};

glui_text_t ui_editor_003_000_009_001_007 =
{
	.base.draw = glui_df_text,
	.base.x = 520,
	.base.width = 116,
	.base.height = 180,
	.base.color = {4294506744, 4294506744},
	.color = {4278190080, 4278190080},
};

glui_text_t ui_editor_003_000_009_001_008 =
{
	.base.draw = glui_df_text,
	.base.x = 636,
	.base.width = 116,
	.base.height = 180,
	.color = {4278190080, 4278190080},
};

glui_dummy_t ui_editor_003_000_009_001_009 =
{
	.base.draw = glui_df_dummy,
	.base.x = 0,
	.base.y = 19,
	.base.width = 752,
	.base.height = 1,
	.base.color = {4279242768, 4279242768},
};

glui_dummy_t ui_editor_003_000_009_001_00A =
{
	.base.draw = glui_df_dummy,
	.base.x = 0,
	.base.y = 20,
	.base.width = 752,
	.base.height = 18,
	.base.color = {134217728, 134217728},
};

glui_dummy_t ui_editor_003_000_009_001_00B =
{
	.base.draw = glui_df_dummy,
	.base.x = 0,
	.base.y = 56,
	.base.width = 752,
	.base.height = 18,
	.base.color = {134217728, 134217728},
};

glui_dummy_t ui_editor_003_000_009_001_00C =
{
	.base.draw = glui_df_dummy,
	.base.x = 0,
	.base.y = 92,
	.base.width = 752,
	.base.height = 18,
	.base.color = {134217728, 134217728},
};

glui_dummy_t ui_editor_003_000_009_001_00D =
{
	.base.draw = glui_df_dummy,
	.base.x = 0,
	.base.y = 128,
	.base.width = 752,
	.base.height = 18,
	.base.color = {134217728, 134217728},
};

glui_dummy_t ui_editor_003_000_009_001_00E =
{
	.base.draw = glui_df_dummy,
	.base.x = 0,
	.base.y = 164,
	.base.width = 752,
	.base.height = 18,
	.base.color = {134217728, 134217728},
};

glui_text_t ui_editor_003_000_009_001_00F =
{
	.base.draw = glui_df_text,
	.base.x = 104,
	.base.y = 190,
	.base.width = 128,
	.base.height = 24,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_thing_state_new,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_003_000_009_001_010 =
{
	.base.draw = glui_df_text,
	.base.x = 280,
	.base.y = 190,
	.base.width = 128,
	.base.height = 24,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_thing_state_ins,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_003_000_009_001_011 =
{
	.base.draw = glui_df_text,
	.base.x = 472,
	.base.y = 190,
	.base.width = 128,
	.base.height = 24,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_thing_state_del,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_thing_state_lnk =
{
	.base.draw = glui_df_text,
	.base.x = 648,
	.base.y = 190,
	.base.width = 128,
	.base.height = 24,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_thing_state_lnk,
	.color = {4290822336, 4294967295},
};

glui_container_t ui_thing_states =
{
	.base.draw = glui_df_container,
	.base.y = 20,
	.count = 1,
	.elements =
	{
		NULL,
	},
};

glui_container_t ui_thing_state_table =
{
	.base.draw = glui_df_container,
	.base.x = 8,
	.base.y = 24,
	.base.width = 752,
	.base.height = 182,
	.base.color = {4294967295, 4294967295},
	.count = 20,
	.elements =
	{
		(void*)&ui_editor_003_000_009_001_000,
		(void*)&ui_editor_003_000_009_001_001,
		(void*)&ui_editor_003_000_009_001_002,
		(void*)&ui_editor_003_000_009_001_003,
		(void*)&ui_editor_003_000_009_001_004,
		(void*)&ui_editor_003_000_009_001_005,
		(void*)&ui_editor_003_000_009_001_006,
		(void*)&ui_editor_003_000_009_001_007,
		(void*)&ui_editor_003_000_009_001_008,
		(void*)&ui_editor_003_000_009_001_009,
		(void*)&ui_editor_003_000_009_001_00A,
		(void*)&ui_editor_003_000_009_001_00B,
		(void*)&ui_editor_003_000_009_001_00C,
		(void*)&ui_editor_003_000_009_001_00D,
		(void*)&ui_editor_003_000_009_001_00E,
		(void*)&ui_editor_003_000_009_001_00F,
		(void*)&ui_editor_003_000_009_001_010,
		(void*)&ui_editor_003_000_009_001_011,
		(void*)&ui_thing_state_lnk,
		(void*)&ui_thing_states,
	},
};

glui_container_t ui_editor_003_000_009 =
{
	.base.draw = glui_df_container,
	.base.x = 16,
	.base.y = 752,
	.base.width = 768,
	.base.height = 246,
	.base.align = GLUI_ALIGN_LEFT_BOT,
	.base.color = {4279242768, 4279242768},
	.count = 2,
	.elements =
	{
		(void*)&ui_thing_state_anim,
		(void*)&ui_thing_state_table,
	},
};

glui_container_t ui_edit_thing_edit =
{
	.base.draw = glui_df_container,
	.count = 10,
	.elements =
	{
		(void*)&ui_thing_state_preview,
		(void*)&ui_thing_state_origin,
		(void*)&ui_thing_idx,
		(void*)&ui_thing_title,
		(void*)&ui_editor_003_000_004,
		(void*)&ui_editor_003_000_005,
		(void*)&ui_thing_attrs,
		(void*)&ui_thing_flags,
		(void*)&ui_thing_anims,
		(void*)&ui_editor_003_000_009,
	},
};

glui_container_t ui_edit_thg =
{
	.base.draw = glui_df_container,
	.base.disabled = 1,
	.input = uin_thing_input,
	.priority = 100,
	.count = 1,
	.elements =
	{
		(void*)&ui_edit_thing_edit,
	},
};

glui_container_t ui_edit_status =
{
	.base.draw = glui_df_container,
	.base.disabled = 1,
	.count = 5,
	.elements =
	{
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
	},
};

glui_text_t ui_editor_005_000 =
{
	.base.draw = glui_df_text,
	.base.x = 260,
	.color = {4278214911, 4278214911},
};

glui_text_t ui_editor_005_001 =
{
	.base.draw = glui_df_text,
	.base.x = 260,
	.base.y = 40,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_map_opt_grpsel,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_005_002 =
{
	.base.draw = glui_df_text,
	.base.x = 260,
	.base.y = 104,
	.color = {4294967295, 4294967295},
};

glui_dummy_t ui_editor_005_003 =
{
	.base.draw = glui_df_dummy,
	.base.x = 260,
	.base.y = 128,
	.base.width = 160,
	.base.height = 120,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4278190080, 4278190080},
};

glui_text_t ui_editor_005_004 =
{
	.base.draw = glui_df_text,
	.base.x = 260,
	.base.y = 128,
	.base.width = 160,
	.base.height = 120,
	.base.align = GLUI_ALIGN_CENTER,
	.color = {4286611584, 4286611584},
};

glui_image_t ui_map_opt_load_image =
{
	.base.draw = glui_df_image,
	.base.x = 260,
	.base.y = 128,
	.base.width = 160,
	.base.height = 120,
	.base.align = GLUI_ALIGN_CENTER,
	.base.click = uin_map_opt_load_image,
	.shader = SHADER_FRAGMENT_PALETTE,
	.coord.s[0] = 0,
	.coord.t[0] = 0,
	.coord.s[1] = 1,
	.coord.t[1] = 1,
};

glui_text_t ui_map_opt_sky_name =
{
	.base.draw = glui_df_text,
	.base.x = 260,
	.base.y = 272,
	.color = {4294967295, 4294967295},
};

glui_dummy_t ui_editor_005_007 =
{
	.base.draw = glui_df_dummy,
	.base.x = 260,
	.base.y = 296,
	.base.width = 512,
	.base.height = 120,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4278190080, 4278190080},
};

glui_text_t ui_editor_005_008 =
{
	.base.draw = glui_df_text,
	.base.x = 260,
	.base.y = 296,
	.base.width = 512,
	.base.height = 120,
	.base.align = GLUI_ALIGN_CENTER,
	.color = {4286611584, 4286611584},
};

glui_image_t ui_map_opt_sky_texture =
{
	.base.draw = glui_df_image,
	.base.x = 260,
	.base.y = 296,
	.base.width = 512,
	.base.height = 120,
	.base.align = GLUI_ALIGN_CENTER,
	.shader = SHADER_FRAGMENT_PALETTE,
	.coord.s[0] = 0,
	.coord.t[0] = 0,
	.coord.s[1] = 1,
	.coord.t[1] = 1,
};

glui_container_t ui_map_menu =
{
	.base.draw = glui_df_container,
	.base.x = 512,
	.base.y = 384,
	.base.width = 520,
	.base.height = 432,
	.base.align = GLUI_ALIGN_CENTER_CENTER,
	.base.disabled = 1,
	.base.color = {4279242768, 4279242768},
	.base.border_size = 2,
	.base.border_color = {4278239424, 4278239424},
	.input = uin_map_opt_input,
	.priority = 200,
	.count = 10,
	.elements =
	{
		(void*)&ui_editor_005_000,
		(void*)&ui_editor_005_001,
		(void*)&ui_editor_005_002,
		(void*)&ui_editor_005_003,
		(void*)&ui_editor_005_004,
		(void*)&ui_map_opt_load_image,
		(void*)&ui_map_opt_sky_name,
		(void*)&ui_editor_005_007,
		(void*)&ui_editor_005_008,
		(void*)&ui_map_opt_sky_texture,
	},
};

glui_text_t ui_editor_006_000 =
{
	.base.draw = glui_df_text,
	.base.x = 128,
	.color = {4278214911, 4278214911},
};

glui_text_t ui_menu_new =
{
	.base.draw = glui_df_text,
	.base.x = 128,
	.base.y = 76,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4278190080, 4278196288},
	.base.click = uin_menu_new,
	.color = {4290822336, 4278255615},
};

glui_text_t ui_menu_load =
{
	.base.draw = glui_df_text,
	.base.x = 128,
	.base.y = 116,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4278190080, 4278196288},
	.base.click = uin_menu_load,
	.color = {4290822336, 4278255615},
};

glui_text_t ui_menu_save =
{
	.base.draw = glui_df_text,
	.base.x = 128,
	.base.y = 156,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4278190080, 4278196288},
	.base.click = uin_menu_save,
	.color = {4290822336, 4278255615},
};

glui_text_t ui_editor_006_004 =
{
	.base.draw = glui_df_text,
	.base.x = 128,
	.base.y = 196,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4278190080, 4278196288},
	.base.click = uin_menu_save_as,
	.color = {4290822336, 4278255615},
};

glui_text_t ui_menu_export =
{
	.base.draw = glui_df_text,
	.base.x = 128,
	.base.y = 236,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4278190080, 4278196288},
	.base.click = uin_menu_export,
	.color = {4290822336, 4278255615},
};

glui_text_t ui_map_options =
{
	.base.draw = glui_df_text,
	.base.x = 128,
	.base.y = 276,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4278190080, 4278196288},
	.base.click = uin_map_options,
	.color = {4290822336, 4278255615},
};

glui_text_t ui_editor_006_007_000 =
{
	.base.draw = glui_df_text,
	.base.x = 128,
	.base.y = 336,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4278190080, 4278196288},
	.base.click = uin_menu_mode,
	.color = {4290822336, 4278255615},
};

glui_text_t ui_editor_006_007_001 =
{
	.base.draw = glui_df_text,
	.base.x = 128,
	.base.y = 376,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4278190080, 4278196288},
	.base.click = uin_menu_mode,
	.color = {4290822336, 4278255615},
};

glui_container_t ui_menu_mode_btns =
{
	.base.draw = glui_df_container,
	.count = 2,
	.elements =
	{
		(void*)&ui_editor_006_007_000,
		(void*)&ui_editor_006_007_001,
	},
};

glui_text_t ui_editor_006_008 =
{
	.base.draw = glui_df_text,
	.base.x = 128,
	.base.y = 436,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4278190080, 4278196288},
	.base.click = uin_menu_generate_tables,
	.color = {4290822336, 4278255615},
};

glui_text_t ui_editor_006_009 =
{
	.base.draw = glui_df_text,
	.base.x = 128,
	.base.y = 476,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4278190080, 4278196288},
	.base.click = uin_menu_exit,
	.color = {4290822336, 4278255615},
};

glui_container_t ui_main_menu =
{
	.base.draw = glui_df_container,
	.base.x = 512,
	.base.y = 384,
	.base.width = 256,
	.base.height = 532,
	.base.align = GLUI_ALIGN_CENTER_CENTER,
	.base.disabled = 1,
	.base.color = {4279242768, 4279242768},
	.base.border_size = 2,
	.base.border_color = {4290822144, 4290822144},
	.input = uin_main_menu_input,
	.priority = 200,
	.count = 10,
	.elements =
	{
		(void*)&ui_editor_006_000,
		(void*)&ui_menu_new,
		(void*)&ui_menu_load,
		(void*)&ui_menu_save,
		(void*)&ui_editor_006_004,
		(void*)&ui_menu_export,
		(void*)&ui_map_options,
		(void*)&ui_menu_mode_btns,
		(void*)&ui_editor_006_008,
		(void*)&ui_editor_006_009,
	},
};

glui_text_t ui_file_select_title =
{
	.base.draw = glui_df_text,
	.base.x = 403,
	.base.y = 5,
	.color = {4294967295, 4294967295},
};

glui_text_t ui_file_select_path =
{
	.base.draw = glui_df_text,
	.base.x = 403,
	.base.y = 594,
	.color = {4290822336, 4290822336},
};

glui_dummy_t ui_editor_007_004 =
{
	.base.draw = glui_df_dummy,
	.base.y = 31,
	.base.width = 806,
	.base.border_size = 1,
	.base.border_color = {4290822144, 4290822144},
};

glui_dummy_t ui_editor_007_005 =
{
	.base.draw = glui_df_dummy,
	.base.y = 592,
	.base.width = 806,
	.base.border_size = 1,
	.base.border_color = {4290822144, 4290822144},
};

glui_container_t ui_file_select =
{
	.base.draw = glui_df_container,
	.base.x = 512,
	.base.y = 384,
	.base.width = 806,
	.base.height = 612,
	.base.align = GLUI_ALIGN_CENTER_CENTER,
	.base.disabled = 1,
	.base.color = {4279242768, 4279242768},
	.base.border_size = 2,
	.base.border_color = {4290822144, 4290822144},
	.priority = 205,
	.count = 6,
	.elements =
	{
		NULL,
		NULL,
		(void*)&ui_file_select_title,
		(void*)&ui_file_select_path,
		(void*)&ui_editor_007_004,
		(void*)&ui_editor_007_005,
	},
};

glui_text_t ui_block_bits_title =
{
	.base.draw = glui_df_text,
	.base.x = 192,
	.base.y = 5,
	.color = {4294967295, 4294967295},
};

glui_text_t ui_editor_008_001 =
{
	.base.draw = glui_df_text,
	.base.x = 192,
	.base.y = 328,
	.base.width = 192,
	.base.height = 32,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_block_bits_save,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_008_002_000 =
{
	.base.draw = glui_df_text,
	.base.x = 192,
	.base.y = 48,
	.base.width = 192,
	.base.height = 24,
	.base.align = GLUI_ALIGN_CENTER,
	.base.custom = 0,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_block_bit_tgl,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_008_002_001 =
{
	.base.draw = glui_df_text,
	.base.x = 192,
	.base.y = 80,
	.base.width = 192,
	.base.height = 24,
	.base.align = GLUI_ALIGN_CENTER,
	.base.custom = 1,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_block_bit_tgl,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_008_002_002 =
{
	.base.draw = glui_df_text,
	.base.x = 192,
	.base.y = 112,
	.base.width = 192,
	.base.height = 24,
	.base.align = GLUI_ALIGN_CENTER,
	.base.custom = 2,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_block_bit_tgl,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_008_002_003 =
{
	.base.draw = glui_df_text,
	.base.x = 192,
	.base.y = 144,
	.base.width = 192,
	.base.height = 24,
	.base.align = GLUI_ALIGN_CENTER,
	.base.custom = 3,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_block_bit_tgl,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_008_002_004 =
{
	.base.draw = glui_df_text,
	.base.x = 192,
	.base.y = 176,
	.base.width = 192,
	.base.height = 24,
	.base.align = GLUI_ALIGN_CENTER,
	.base.custom = 4,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_block_bit_tgl,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_008_002_005 =
{
	.base.draw = glui_df_text,
	.base.x = 192,
	.base.y = 208,
	.base.width = 192,
	.base.height = 24,
	.base.align = GLUI_ALIGN_CENTER,
	.base.custom = 5,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_block_bit_tgl,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_008_002_006 =
{
	.base.draw = glui_df_text,
	.base.x = 192,
	.base.y = 240,
	.base.width = 192,
	.base.height = 24,
	.base.align = GLUI_ALIGN_CENTER,
	.base.custom = 6,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_block_bit_tgl,
	.color = {4290822336, 4294967295},
};

glui_text_t ui_editor_008_002_007 =
{
	.base.draw = glui_df_text,
	.base.x = 192,
	.base.y = 272,
	.base.width = 192,
	.base.height = 24,
	.base.align = GLUI_ALIGN_CENTER,
	.base.custom = 7,
	.base.color = {4280295456, 4286611584},
	.base.click = uin_block_bit_tgl,
	.color = {4290822336, 4294967295},
};

glui_container_t ui_block_bit_btns =
{
	.base.draw = glui_df_container,
	.count = 8,
	.elements =
	{
		(void*)&ui_editor_008_002_000,
		(void*)&ui_editor_008_002_001,
		(void*)&ui_editor_008_002_002,
		(void*)&ui_editor_008_002_003,
		(void*)&ui_editor_008_002_004,
		(void*)&ui_editor_008_002_005,
		(void*)&ui_editor_008_002_006,
		(void*)&ui_editor_008_002_007,
	},
};

glui_container_t ui_block_bits =
{
	.base.draw = glui_df_container,
	.base.x = 512,
	.base.y = 384,
	.base.width = 384,
	.base.height = 384,
	.base.align = GLUI_ALIGN_CENTER_CENTER,
	.base.disabled = 1,
	.base.color = {4279242768, 4279242768},
	.base.border_size = 2,
	.base.border_color = {4290797568, 4290797568},
	.input = uin_block_bits_input,
	.priority = 208,
	.count = 3,
	.elements =
	{
		(void*)&ui_block_bits_title,
		(void*)&ui_editor_008_001,
		(void*)&ui_block_bit_btns,
	},
};

glui_text_t ui_textentry_title =
{
	.base.draw = glui_df_text,
	.base.x = 192,
	.base.y = 5,
	.color = {4294967295, 4294967295},
};

glui_dummy_t ui_editor_009_001 =
{
	.base.draw = glui_df_dummy,
	.base.x = 0,
	.base.y = 32,
	.base.width = 384,
	.base.height = 24,
	.base.color = {4294967295, 4294967295},
	.base.border_size = 2,
	.base.border_color = {4290773088, 4290773088},
};

glui_text_t ui_textentry_text =
{
	.base.draw = glui_df_text,
	.base.x = 4,
	.base.y = 32,
	.color = {4278190080, 4278190080},
};

glui_text_t ui_editor_009_003 =
{
	.base.draw = glui_df_text,
	.base.x = 96,
	.base.y = 60,
	.base.width = 128,
	.base.height = 24,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4278190080, 4281348144},
	.base.click = uin_textentry_ok,
	.color = {4286611584, 4294967295},
};

glui_text_t ui_editor_009_004 =
{
	.base.draw = glui_df_text,
	.base.x = 288,
	.base.y = 60,
	.base.width = 128,
	.base.height = 24,
	.base.align = GLUI_ALIGN_CENTER,
	.base.color = {4278190080, 4281348144},
	.base.click = uin_textentry_ko,
	.color = {4286611584, 4294967295},
};

glui_container_t ui_textentry =
{
	.base.draw = glui_df_container,
	.base.x = 512,
	.base.y = 384,
	.base.width = 384,
	.base.height = 88,
	.base.align = GLUI_ALIGN_CENTER_CENTER,
	.base.disabled = 1,
	.base.color = {4279242768, 4279242768},
	.base.border_size = 2,
	.base.border_color = {4290773088, 4290773088},
	.priority = 209,
	.count = 5,
	.elements =
	{
		(void*)&ui_textentry_title,
		(void*)&ui_editor_009_001,
		(void*)&ui_textentry_text,
		(void*)&ui_editor_009_003,
		(void*)&ui_editor_009_004,
	},
};

glui_text_t ui_question_title =
{
	.base.draw = glui_df_text,
	.base.x = 256,
	.base.y = 5,
	.color = {4294967295, 4294967295},
};

glui_text_t ui_question_text =
{
	.base.draw = glui_df_text,
	.base.x = 256,
	.base.y = 96,
	.color = {4290822336, 4290822336},
};

glui_dummy_t ui_editor_00A_002 =
{
	.base.draw = glui_df_dummy,
	.base.y = 32,
	.base.width = 512,
	.base.border_size = 1,
	.base.border_color = {4290822144, 4290822144},
};

glui_text_t ui_editor_00A_003 =
{
	.base.draw = glui_df_text,
	.base.x = 160,
	.base.y = 186,
	.base.width = 128,
	.base.height = 24,
	.base.align = GLUI_ALIGN_CENTER_BOT,
	.base.color = {4278190080, 4281348144},
	.base.click = uin_question_yes,
	.color = {4286611584, 4294967295},
};

glui_text_t ui_editor_00A_004 =
{
	.base.draw = glui_df_text,
	.base.x = 352,
	.base.y = 186,
	.base.width = 128,
	.base.height = 24,
	.base.align = GLUI_ALIGN_CENTER_BOT,
	.base.color = {4278190080, 4281348144},
	.base.click = uin_question_no,
	.color = {4286611584, 4294967295},
};

glui_container_t ui_question =
{
	.base.draw = glui_df_container,
	.base.x = 512,
	.base.y = 384,
	.base.width = 512,
	.base.height = 192,
	.base.align = GLUI_ALIGN_CENTER_CENTER,
	.base.disabled = 1,
	.base.color = {4279242768, 4279242768},
	.base.border_size = 2,
	.base.border_color = {4290822144, 4290822144},
	.priority = 210,
	.count = 5,
	.elements =
	{
		(void*)&ui_question_title,
		(void*)&ui_question_text,
		(void*)&ui_editor_00A_002,
		(void*)&ui_editor_00A_003,
		(void*)&ui_editor_00A_004,
	},
};

glui_container_t ui_editor =
{
	.base.draw = glui_df_container,
	.count = 11,
	.elements =
	{
		(void*)&ui_edit_mode,
		(void*)&ui_edit_highlight,
		(void*)&ui_edit_gfx,
		(void*)&ui_edit_thg,
		(void*)&ui_edit_status,
		(void*)&ui_map_menu,
		(void*)&ui_main_menu,
		(void*)&ui_file_select,
		(void*)&ui_block_bits,
		(void*)&ui_textentry,
		(void*)&ui_question,
	},
};

glui_text_t ui_busy_text =
{
	.base.draw = glui_df_text,
	.base.x = 256,
	.base.y = 96,
	.color = {4294967295, 4294967295},
};

glui_container_t ui_busy_window =
{
	.base.draw = glui_df_container,
	.base.x = 512,
	.base.y = 384,
	.base.width = 512,
	.base.height = 192,
	.base.align = GLUI_ALIGN_CENTER_CENTER,
	.base.color = {4279242768, 4279242768},
	.base.border_size = 2,
	.base.border_color = {4290822336, 4290822336},
	.priority = 255,
	.count = 1,
	.elements =
	{
		(void*)&ui_busy_text,
	},
};

const glui_init_text_t glui_init_text[GLUI_INIT_TEXT] =
{
	{
		.elm = &ui_edit_mode,
	},
	{
		.elm = &ui_edit_highlight_title,
	},
	{
		.elm = &ui_edit_highlight_textA,
	},
	{
		.elm = &ui_edit_highlight_textB,
	},
	{
		.elm = &ui_edit_highlight_textC,
	},
	{
		.elm = &ui_edit_highlight_textD,
	},
	{
		.elm = &ui_editor_002_000_001,
		.text = "Import from PNG",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_000_002,
		.text = "desaturate",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_palette_tint_des,
	},
	{
		.elm = &ui_editor_002_000_004,
		.text = "multiply",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_palette_tint_mr,
	},
	{
		.elm = &ui_gfx_palette_tint_mg,
	},
	{
		.elm = &ui_gfx_palette_tint_mb,
	},
	{
		.elm = &ui_editor_002_000_008,
		.text = "add",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_palette_tint_ar,
	},
	{
		.elm = &ui_gfx_palette_tint_ag,
	},
	{
		.elm = &ui_gfx_palette_tint_ab,
	},
	{
		.elm = &ui_editor_002_000_00C,
		.text = "Apply tint",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_000_00D,
		.text = "desaturate",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_palette_dmg_des,
	},
	{
		.elm = &ui_editor_002_000_00F,
		.text = "add",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_palette_dmg_add,
	},
	{
		.elm = &ui_editor_002_000_011,
		.text = "color",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_palette_dmg_r,
	},
	{
		.elm = &ui_gfx_palette_dmg_g,
	},
	{
		.elm = &ui_gfx_palette_dmg_b,
	},
	{
		.elm = &ui_editor_002_000_015,
		.text = "Generate damage tint",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_000_016,
		.text = "Generate damage all",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_001_000,
		.text = "New light",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_001_001,
		.text = "Rename light",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_001_002,
		.text = "Delete light",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_light_des,
	},
	{
		.elm = &ui_gfx_light_r,
	},
	{
		.elm = &ui_gfx_light_g,
	},
	{
		.elm = &ui_gfx_light_b,
	},
	{
		.elm = &ui_editor_002_002_000_000_000,
		.text = "first",
		.font = glui_font_small_kfn,
		.align = GLUI_ALIGN_CENTER,
	},
	{
		.elm = &ui_editor_002_002_000_000_001,
		.text = "last",
		.font = glui_font_small_kfn,
		.align = GLUI_ALIGN_CENTER,
	},
	{
		.elm = &ui_editor_002_002_000_000_002,
		.text = "start",
		.font = glui_font_small_kfn,
		.align = GLUI_ALIGN_CENTER,
	},
	{
		.elm = &ui_editor_002_002_000_000_003,
		.text = "stop",
		.font = glui_font_small_kfn,
		.align = GLUI_ALIGN_CENTER,
	},
	{
		.elm = &ui_editor_002_002_000_000_009,
		.text = "New range",
		.font = glui_font_small_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_002_000_000_00A,
		.text = "Delete range",
		.font = glui_font_small_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_remap_color,
	},
	{
		.elm = &ui_gfx_plane_variant_name,
	},
	{
		.elm = &ui_editor_002_003_001,
		.text = "New 4bpp plane",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_003_002,
		.text = "New 8bpp plane",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_003_003,
		.text = "Rename plane",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_003_004,
		.text = "Delete plane",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_003_005,
		.text = "Import PNG Auto",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_plane_import_raw,
		.text = "Import PNG RAW",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_plane_variant,
		.text = "New variant",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_plane_renvar,
		.text = "Rename variant",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_plane_delvar,
		.text = "Delete variant",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_plane_display,
	},
	{
		.elm = &ui_editor_002_003_00B_000,
	},
	{
		.elm = &ui_editor_002_003_00B_001,
	},
	{
		.elm = &ui_editor_002_003_00B_002,
	},
	{
		.elm = &ui_editor_002_003_00B_003,
	},
	{
		.elm = &ui_gfx_plane_variant_pl,
		.text = ">",
		.font = glui_font_huge_kfn,
		.align = GLUI_ALIGN_RIGHT_CENTER,
	},
	{
		.elm = &ui_gfx_plane_variant_pr,
		.text = "<",
		.font = glui_font_huge_kfn,
		.align = GLUI_ALIGN_LEFT_CENTER,
	},
	{
		.elm = &ui_gfx_wall_variant_name,
	},
	{
		.elm = &ui_gfx_wall_variant_info,
	},
	{
		.elm = &ui_gfx_wall_resolution,
	},
	{
		.elm = &ui_gfx_wall_info,
	},
	{
		.elm = &ui_editor_002_004_004,
		.text = ">",
		.font = glui_font_huge_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_004_005,
		.text = "<",
		.font = glui_font_huge_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_wall_import_raw,
		.text = "Import PNG RAW",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_004_007,
		.text = "New wall",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_004_008,
		.text = "Rename wall",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_004_009,
		.text = "Delete wall",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_004_00A,
		.text = "Import PNG auto",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_004_00B,
		.text = "New variant",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_004_00C,
		.text = "Rename variant",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_004_00D,
		.text = "Delete variant",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_004_00E,
		.text = "Make all fullbright",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_wall_display,
	},
	{
		.elm = &ui_editor_002_004_010_000,
	},
	{
		.elm = &ui_editor_002_004_010_001,
	},
	{
		.elm = &ui_editor_002_004_010_002,
	},
	{
		.elm = &ui_gfx_sprite_variant_name,
	},
	{
		.elm = &ui_gfx_sprite_variant_info,
	},
	{
		.elm = &ui_gfx_sprite_resolution,
	},
	{
		.elm = &ui_gfx_sprite_info,
	},
	{
		.elm = &ui_editor_002_005_006,
		.text = "Offset X",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_005_007,
		.text = "Offset Y",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_005_008,
		.text = ">",
		.font = glui_font_huge_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_005_009,
		.text = "<",
		.font = glui_font_huge_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_sprite_import_raw,
		.text = "Import PNG RAW",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_005_00B,
		.text = "New sprite",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_005_00C,
		.text = "Rename sprite",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_005_00D,
		.text = "Delete sprite",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_005_00E,
		.text = "Import PNG auto",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_005_00F,
		.text = "New variant",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_005_010,
		.text = "Rename variant",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_005_011,
		.text = "Delete variant",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_sprite_show_origin,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_005_013,
		.text = "Mirror this variant",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_sprite_offs_x,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_sprite_offs_y,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_sprite_display,
	},
	{
		.elm = &ui_gfx_wpn_variant_name,
	},
	{
		.elm = &ui_editor_002_006_001,
		.text = ">",
		.font = glui_font_huge_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_006_002,
		.text = "<",
		.font = glui_font_huge_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_006_003,
		.text = "New sprite",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_006_004,
		.text = "Rename sprite",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_006_005,
		.text = "Delete sprite",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_006_006,
		.text = "Import PNG",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_006_007,
		.text = "New variant",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_wpn_info,
	},
	{
		.elm = &ui_editor_002_006_009,
		.text = "Delete variant",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_wpn_part_pl,
		.text = ">",
		.font = glui_font_huge_kfn,
		.align = GLUI_ALIGN_RIGHT_CENTER,
	},
	{
		.elm = &ui_gfx_wpn_part_pr,
		.text = "<",
		.font = glui_font_huge_kfn,
		.align = GLUI_ALIGN_LEFT_CENTER,
	},
	{
		.elm = &ui_gfx_wpn_part_text_l,
	},
	{
		.elm = &ui_gfx_wpn_part_text_r,
	},
	{
		.elm = &ui_gfx_wpn_part_apply,
		.text = "Apply parts",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_wpn_part_btn0,
	},
	{
		.elm = &ui_gfx_wpn_part_btn1,
	},
	{
		.elm = &ui_gfx_wpn_part_btn2,
	},
	{
		.elm = &ui_editor_002_007_000,
		.text = "Import PNG",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_007_001,
		.text = "New sky",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_007_002,
		.text = "Rename sky",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_007_003,
		.text = "Delete sky",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_008_000,
		.text = "Import PNG",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_hud_color,
	},
	{
		.elm = &ui_gfx_idx,
	},
	{
		.elm = &ui_gfx_title,
	},
	{
		.elm = &ui_editor_002_00B,
		.text = ">",
		.font = glui_font_huge_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_002_00C,
		.text = "<",
		.font = glui_font_huge_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_palette_txt,
		.text = "Palette",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_lights_txt,
		.text = "Lights",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_remaps_txt,
		.text = "Remaps",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_planes_txt,
		.text = "Planes",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_walls_txt,
		.text = "Walls",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_sprites_txt,
		.text = "Sprites",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_weapons_txt,
		.text = "Weapons",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_skies_txt,
		.text = "Skies",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_gfx_hud_txt,
		.text = "HUD",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_thing_idx,
	},
	{
		.elm = &ui_thing_title,
	},
	{
		.elm = &ui_editor_003_000_004,
		.text = ">",
		.font = glui_font_huge_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_003_000_005,
		.text = "<",
		.font = glui_font_huge_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_thing_state_anim,
	},
	{
		.elm = &ui_editor_003_000_009_001_000,
		.text = "index",
		.font = glui_font_small_kfn,
		.align = GLUI_ALIGN_CENTER,
	},
	{
		.elm = &ui_editor_003_000_009_001_001,
		.text = "sprite",
		.font = glui_font_small_kfn,
		.align = GLUI_ALIGN_CENTER,
	},
	{
		.elm = &ui_editor_003_000_009_001_002,
		.text = "frame",
		.font = glui_font_small_kfn,
		.align = GLUI_ALIGN_CENTER,
	},
	{
		.elm = &ui_editor_003_000_009_001_003,
		.text = "ticks",
		.font = glui_font_small_kfn,
		.align = GLUI_ALIGN_CENTER,
	},
	{
		.elm = &ui_editor_003_000_009_001_004,
		.text = "next",
		.font = glui_font_small_kfn,
		.align = GLUI_ALIGN_CENTER,
	},
	{
		.elm = &ui_editor_003_000_009_001_005,
		.text = "action",
		.font = glui_font_small_kfn,
		.align = GLUI_ALIGN_CENTER,
	},
	{
		.elm = &ui_editor_003_000_009_001_006,
		.text = "arg[0]",
		.font = glui_font_small_kfn,
		.align = GLUI_ALIGN_CENTER,
	},
	{
		.elm = &ui_editor_003_000_009_001_007,
		.text = "arg[1]",
		.font = glui_font_small_kfn,
		.align = GLUI_ALIGN_CENTER,
	},
	{
		.elm = &ui_editor_003_000_009_001_008,
		.text = "arg[2]",
		.font = glui_font_small_kfn,
		.align = GLUI_ALIGN_CENTER,
	},
	{
		.elm = &ui_editor_003_000_009_001_00F,
		.text = "New state",
		.font = glui_font_small_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_003_000_009_001_010,
		.text = "Insert state",
		.font = glui_font_small_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_003_000_009_001_011,
		.text = "Delete state",
		.font = glui_font_small_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_thing_state_lnk,
		.text = "Animation link",
		.font = glui_font_small_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_005_000,
		.text = "Map Options",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER,
	},
	{
		.elm = &ui_editor_005_001,
		.text = "Group visibility",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_005_002,
		.text = "Loading Screen",
		.font = glui_font_small_kfn,
		.align = GLUI_ALIGN_CENTER,
	},
	{
		.elm = &ui_editor_005_004,
		.text = "	\n\nClick here to load\nimage from PNG ...",
		.font = glui_font_small_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_map_opt_sky_name,
	},
	{
		.elm = &ui_editor_005_008,
		.text = "Use scroll wheel to select map sky texture ...",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_006_000,
		.text = "kgEdit X16",
		.font = glui_font_huge_kfn,
		.align = GLUI_ALIGN_CENTER,
	},
	{
		.elm = &ui_menu_new,
	},
	{
		.elm = &ui_menu_load,
	},
	{
		.elm = &ui_menu_save,
	},
	{
		.elm = &ui_editor_006_004,
		.text = "Save as",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_menu_export,
	},
	{
		.elm = &ui_map_options,
		.text = "Map Options",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_006_007_000,
	},
	{
		.elm = &ui_editor_006_007_001,
	},
	{
		.elm = &ui_editor_006_008,
		.text = "Generate tables",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_006_009,
		.text = "Exit",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_file_select_title,
	},
	{
		.elm = &ui_file_select_path,
	},
	{
		.elm = &ui_block_bits_title,
	},
	{
		.elm = &ui_editor_008_001,
		.text = "OK",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_008_002_000,
	},
	{
		.elm = &ui_editor_008_002_001,
	},
	{
		.elm = &ui_editor_008_002_002,
	},
	{
		.elm = &ui_editor_008_002_003,
	},
	{
		.elm = &ui_editor_008_002_004,
	},
	{
		.elm = &ui_editor_008_002_005,
	},
	{
		.elm = &ui_editor_008_002_006,
	},
	{
		.elm = &ui_editor_008_002_007,
	},
	{
		.elm = &ui_textentry_title,
	},
	{
		.elm = &ui_textentry_text,
	},
	{
		.elm = &ui_editor_009_003,
		.text = "OK",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_009_004,
		.text = "Cancel",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_question_title,
	},
	{
		.elm = &ui_question_text,
	},
	{
		.elm = &ui_editor_00A_003,
		.text = "Yes",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_editor_00A_004,
		.text = "No",
		.font = glui_font_medium_kfn,
		.align = GLUI_ALIGN_CENTER_CENTER,
	},
	{
		.elm = &ui_busy_text,
	},
};
